EXTERNAL print_error(text)
EXTERNAL bubble(text)
EXTERNAL pick_up(object_id)
EXTERNAL create_object(object_id)
EXTERNAL is_in_inventory(thing_id)
EXTERNAL set_variable(id, value)
EXTERNAL get_variable(name)
EXTERNAL set_name(thing_id, name)
EXTERNAL wait(time)
EXTERNAL move_to(x, y)
EXTERNAL move_relative(x, y)