EXTERNAL print_error(text)
EXTERNAL get_var(name)
EXTERNAL set_var(id, value)
EXTERNAL visited(character_id)
EXTERNAL is_in_inventory(thing_id)
EXTERNAL set_name(thing_id, name)
EXTERNAL pick_up(object_id)
EXTERNAL create(object_id)

EXTERNAL dialog(character_id)
EXTERNAL bubble(text)
EXTERNAL wait(time)
EXTERNAL move_to(x, y)
EXTERNAL move_rel(x, y)
EXTERNAL play_anim(anim_name)
EXTERNAL play_anim_char(character_id, anim_name)